### ISSUE TITLE
Validate registered function

### ISSUE THREAD

**Issue by alexdebrie** [serverless/event-gateway#168]
The AWS SDK allows you to invoke a Lambda function with a `DryRun` InvocationType (see [here](https://github.com/aws/aws-sdk-go/blob/master/service/lambda/api.go#L4967-L4972)). This doesn't actually invoke the function, but it allows you to do some verification that the function exists _and_ that your given credentials are authorized to invoke it.

Should we add this verification on the `registerFunction` endpoint? It might save a lot of user pain for debugging.

I'm not sure if GCP/Azure/OpenWhisk have similar verification methods. Would it be confusing if we verified on AWS but not others?

**Comment by rupakg** [comment]
@alexdebrie I like it, but I also agree with @mthenw The expectation that each provider will have some way to validate is not practical. 

But, I want to highlight the fact that it is an important issue that we should discuss. The registerFunction not throwing an error gives a false sense of security. Since the `registration` of a function can happen way before it is `called`, it is really hard to track down what went wrong. 

It looks like at the time of calling, we need to somehow match the fact that while registering the function did not pass in creds, so it can't be called, and throw a very specific error.

**Comment by mthenw** [comment]
Right now the raw error from AWS SDK is returned, e.g.:

>unable to reach backing function: AccessDeniedException: User: arn:aws:iam::xxx:user/xxx is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:xxx:function:xxx
	status code: 403, request id: 983dd2ed-7b83-11e7-b328-39286bc3927a

Do you think that something more specific should be returned?
