### ISSUE TITLE
architecture comment

### ISSUE THREAD

**Issue by pfeilbr** [serverless/event-gateway#298]
Really appreciate the work that is being done.  Just an observation ...

This whole architecture is based on serverfull / long-lived processes.  Seems to go against the grain of the company.  Assuming a go process will be long lived along with its backing store (consul, zookeeper, etc., whatever docker supports) goes against the grain of serverless, only consuming compute and memory when needed.  The drain, dropped events, etc. seem like concessions, but have extremely large impacts at production scale (go does go a long way with resource efficiency, but there will be use cases that break it ... even with clustgering)  Will the production deployment for a given cloud not require docker and be based on sns, sqs, kinesis, dynamodb (streams) (aws specific) to not require a serverful component?

This "event router" will become the bottle neck.  It's a lot of code, and I'd be more comforted standing on the shoulders of giants (aws, azure, etc) and piecing their services together (glue) vs. a large codebase recreating it (event-gateway router).

I know its early for the product and I don't have the visibility into the roadmap, but just wanted to post and get thoughts.

Thank you,
Brian

**Comment by xtuc** [comment]
A long-living process is needed to guarantee constant throughput. An on-prem based approach would suffer from cold start, latency, ...

Some background jobs require a running process, like the following:
- Delivery retry/delay
- Nodes replication
- Internal log backup or manipulation

> This "event router" will become the bottle neck. It's a lot of code.

It won't, and from my understanding you prefer relying on some cloud provided blackbox rather than a dedicated (open-source) solution.

**Comment by RafalWilinski** [comment]
I have the same impression as @pfeilbr. The fact that I have to spin up a EC2 instance on my own, run a long-running process there and care about a machine kills the whole "serverless magic" for me.

Personally, I'd love to see a hosted/managed event-gateway by Serverless team and it seems that something might be coming: https://github.com/serverless/event-gateway-example/issues/17#issuecomment-323302112

> you prefer relying on some cloud provided blackbox rather than a dedicated (open-source) solution.
I prefer relying on a cloud service rather than on an instance maintained by myself. It doesn't matter for me if it's black box actually.

**Comment by mthenw** [comment]
@pfeilbr @RafalWilinski we really appreciate your feedback. 

We decided to implement the event router because of performance and reliability reasons. It may look like against the grain the company but actually, the goal of the company is to make it easier to build event-driven serverless system. Sometimes it requires building software running on real/virtual servers. 

We are aware that running this by the developers/companies that decided to go 100% serverless is problematic. **That's why we have plans to offer the Event Gateway as a hosted service in the future.**

> Will the production deployment for a given cloud not require docker and be based on sns, sqs, kinesis, dynamodb (streams) (aws specific) to not require a serverful component?

We don't want to provide tools that work only for one cloud provider. EG is provider independent and it will support multiple providers out of the box.

@xtuc thanks for chiming in!
